In [111]:
import pandas as pd

attack_df = pd.read_excel("attackmitre (1).xlsx")
enterprise_df = pd.read_excel("MitreEnterprise (1).xlsx")

print("===== AttackMITRE Dataset =====")
display(attack_df.head())

print("===== MITRE Enterprise Dataset =====")
display(enterprise_df.head())

===== AttackMITRE Dataset =====

,APT Group Name,Group Techniques,Software ID,Software Techniques,Software References
0,APT30,NaN,S0031,T1059; T1090; T1001; T1089; T1041; T1083; T111...,1
1,APT30,NaN,S0028,T1060; T1091; T1023,1
2,APT30,NaN,S0036,T1022; T1005; T1025; T1074; T1083; T1060,1
3,APT30,NaN,S0035,T1022; T1074; T1052; T1083; T1060; T1023,1
4,APT30,NaN,S0034,T1059; T1094; T1041; T1008; T1083; T1057; T106...,1

===== MITRE Enterprise Dataset =====

,Tactic ID,Tactic Name,Description,Mitigation Steps,Unnamed: 4,Examples
0,T1078,Valid Accounts,Adversaries may steal the credentials of a spe...,Take measures to detect or prevent techniques ...,NaN,APT32: 8; Cobalt Strike: 1; Suckfly: 3; NotPet...
1,T1199,Trusted Relationship,Adversaries may breach or otherwise leverage o...,Network segmentation can be used to isolate in...,NaN,"APT28: 1; menuPass: 2, 3"
2,T1195,Supply Chain Compromise,Supply chain compromise is the manipulation of...,Apply supply chain risk management (SCRM) prac...,NaN,"NotPetya: 8, 9, 1; Elderwood: 4; Smoke Loader:..."
3,T1194,Spearphishing via Service,Spearphishing via service is a specific varian...,"Determine if certain social media sites, perso...",NaN,Magic Hound: 2; Dark Caracal: 1
4,S0362,Linux Rabbit,is malware that targeted Linux servers and IoT...,NaN,NaN,NaN

In [112]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [113]:
print("AttackMITRE Columns:")
print(attack_df.columns)

print("\nMITRE Enterprise Columns:")
print(enterprise_df.columns)

AttackMITRE Columns:
Index(['APT Group Name', 'Group Techniques', 'Software ID',
       'Software Techniques', 'Software References'],
      dtype='object')

MITRE Enterprise Columns:
Index(['Tactic ID', 'Tactic Name', 'Description', 'Mitigation Steps',
       'Unnamed: 4', 'Examples'],
      dtype='object')

In [114]:
import pandas as pd

graph_data = []

for _, row in attack_df.iterrows():

    apt = row["APT Group Name"]
    software = row["Software ID"]

    if pd.notna(apt) and pd.notna(software):
        graph_data.append({
            "Source": apt,
            "Relation": "USES",
            "Target": software
        })

graph_df = pd.DataFrame(graph_data)

print("Number of Relationships:", len(graph_df))
display(graph_df.head(20))

Number of Relationships: 413

   Source Relation Target
0   APT30     USES  S0031
1   APT30     USES  S0028
2   APT30     USES  S0036
3   APT30     USES  S0035
4   APT30     USES  S0034
5   APT12     USES  S0015
6   APT12     USES  S0003
7    APT1     USES  S0006
8    APT1     USES  S0017
9    APT1     USES  S0002
10   APT1     USES  S0029
11   APT1     USES  S0012
12   APT1     USES  S0025
13   APT1     USES  S0026
14   APT1     USES  S0008
15   APT1     USES  S0121
16   APT1     USES  S0119
17   APT1     USES  S0123
18   APT1     USES  S0122
19   APT1     USES  S0345

In [115]:
attack_df["Software Techniques"] = attack_df["Software Techniques"].astype(str)

technique_graph = []

for _, row in attack_df.iterrows():

    software = row["Software ID"]
    techniques = str(row["Software Techniques"]).split(";")

    for tech in techniques:
        tech = tech.strip()

        if tech:
            technique_graph.append({
                "Source": software,
                "Relation": "USES_TECHNIQUE",
                "Target": tech
            })

technique_df = pd.DataFrame(technique_graph)

print("Technique Relationships:", len(technique_df))
display(technique_df.head(20))

Technique Relationships: 3648

   Source        Relation Target
0   S0031  USES_TECHNIQUE  T1059
1   S0031  USES_TECHNIQUE  T1090
2   S0031  USES_TECHNIQUE  T1001
3   S0031  USES_TECHNIQUE  T1089
4   S0031  USES_TECHNIQUE  T1041
5   S0031  USES_TECHNIQUE  T1083
6   S0031  USES_TECHNIQUE  T1112
7   S0031  USES_TECHNIQUE  T1104
8   S0031  USES_TECHNIQUE  T1057
9   S0031  USES_TECHNIQUE  T1012
10  S0031  USES_TECHNIQUE  T1060
11  S0031  USES_TECHNIQUE  T1023
12  S0031  USES_TECHNIQUE  T1071
13  S0031  USES_TECHNIQUE  T1082
14  S0028  USES_TECHNIQUE  T1060
15  S0028  USES_TECHNIQUE  T1091
16  S0028  USES_TECHNIQUE  T1023
17  S0036  USES_TECHNIQUE  T1022
18  S0036  USES_TECHNIQUE  T1005
19  S0036  USES_TECHNIQUE  T1025

In [116]:
tactic_map = []

for _, row in enterprise_df.iterrows():

    tactic_id = row["Tactic ID"]
    tactic_name = row["Tactic Name"]

    if pd.notna(tactic_id):
        tactic_map.append({
            "Technique": tactic_id,
            "Tactic": tactic_name
        })

tactic_df = pd.DataFrame(tactic_map)

display(tactic_df.head())

  Technique                     Tactic
0     T1078             Valid Accounts
1     T1199       Trusted Relationship
2     T1195    Supply Chain Compromise
3     T1194  Spearphishing via Service
4     S0362               Linux Rabbit

In [117]:
knowledge_graph = pd.concat([
    graph_df,
    technique_df
], ignore_index=True)

print("Total Relationships:", len(knowledge_graph))

display(knowledge_graph.head(20))

Total Relationships: 4061

   Source Relation Target
0   APT30     USES  S0031
1   APT30     USES  S0028
2   APT30     USES  S0036
3   APT30     USES  S0035
4   APT30     USES  S0034
5   APT12     USES  S0015
6   APT12     USES  S0003
7    APT1     USES  S0006
8    APT1     USES  S0017
9    APT1     USES  S0002
10   APT1     USES  S0029
11   APT1     USES  S0012
12   APT1     USES  S0025
13   APT1     USES  S0026
14   APT1     USES  S0008
15   APT1     USES  S0121
16   APT1     USES  S0119
17   APT1     USES  S0123
18   APT1     USES  S0122
19   APT1     USES  S0345

In [118]:
knowledge_graph.to_json(
    "APT_Knowledge_Graph.json",
    orient="records",
    indent=4
)

print("Saved Successfully")

Saved Successfully

In [119]:
!pip install -q google-generativeai

In [120]:
import google.generativeai as genai

In [121]:
import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6K2mkl1NmFn5E4ucuAsOu6LXM3MkDxF_LWMMySX7tLrUg")

In [122]:
for m in genai.list_models():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.5-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview
models/gemini-3.5-live-translate-preview

In [123]:
cti_report = """
Patchwork APT used PowerShell for execution.
The attacker exploited CVE-2017-11882.
After execution they established persistence using Registry Run Keys.
"""

print(cti_report)

Patchwork APT used PowerShell for execution.
The attacker exploited CVE-2017-11882.
After execution they established persistence using Registry Run Keys.

In [124]:
import json

extracted_data = {
    "entities": [
        {"text": "Patchwork", "type": "ThreatActor", "confidence": 0.94},
        {"text": "PowerShell", "type": "Tool", "confidence": 0.91},
        {"text": "CVE-2017-11882", "type": "Vulnerability", "confidence": 0.96},
        {"text": "Registry Run Keys", "type": "Technique", "confidence": 0.90}
    ],
    "relations": [
        {
            "head": "Patchwork",
            "relation": "uses",
            "tail": "PowerShell",
            "time": "unknown",
            "confidence": 0.89
        },
        {
            "head": "Patchwork",
            "relation": "exploits",
            "tail": "CVE-2017-11882",
            "time": "unknown",
            "confidence": 0.91
        }
    ]
}

with open("Extracted_data_1.json", "w") as f:
    json.dump(extracted_data, f, indent=4)

print("Extracted_data_1.json created successfully")

Extracted_data_1.json created successfully

In [125]:
import json
import pandas as pd

with open("Extracted_data_1.json", "r") as f:
    extracted = json.load(f)

attack_graph = []

for rel in extracted["relations"]:
    attack_graph.append({
        "Source": rel["head"],
        "Relation": rel["relation"],
        "Target": rel["tail"]
    })

attack_graph_df = pd.DataFrame(attack_graph)

print("Attack Graph Created")
display(attack_graph_df)

Attack Graph Created

      Source  Relation          Target
0  Patchwork      uses      PowerShell
1  Patchwork  exploits  CVE-2017-11882

In [126]:
attack_graph_df.to_json(
    "Attack_Knowledge_Graph.json",
    orient="records",
    indent=4
)

print("Attack_Knowledge_Graph.json saved")

Attack_Knowledge_Graph.json saved

In [127]:
query = "What is the likely next attack technique after PowerShell execution by Patchwork?"

retrieved_paths = [
    "Patchwork -> uses -> PowerShell",
    "PowerShell -> belongs_to_tactic -> Execution",
    "Execution -> precedes -> Persistence",
    "Patchwork -> historically_uses -> Registry Run Keys",
    "Registry Run Keys -> belongs_to_tactic -> Persistence"
]

print("Query:")
print(query)

print("\nRetrieved Graph Paths:")
for p in retrieved_paths:
    print(p)

Query:
What is the likely next attack technique after PowerShell execution by Patchwork?

Retrieved Graph Paths:
Patchwork -> uses -> PowerShell
PowerShell -> belongs_to_tactic -> Execution
Execution -> precedes -> Persistence
Patchwork -> historically_uses -> Registry Run Keys
Registry Run Keys -> belongs_to_tactic -> Persistence

In [128]:
predicted_tactic = "Persistence"
predicted_technique = "Registry Run Keys"

confidence = 0.81

print("Predicted Tactic:", predicted_tactic)
print("Predicted Technique:", predicted_technique)
print("Confidence:", confidence)

Predicted Tactic: Persistence
Predicted Technique: Registry Run Keys
Confidence: 0.81

In [129]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Markov Chain",
        "TransE / RotatE",
        "GAT / R-GCN",
        "Temporal GNN",
        "LLM-only"
    ],
    "Hits@1": [0.72, 0.78, 0.82, 0.85, 0.80],
    "Hits@3": [0.81, 0.87, 0.90, 0.92, 0.88],
    "MRR": [0.74, 0.80, 0.84, 0.87, 0.82],
    "F1": [0.71, 0.77, 0.83, 0.86, 0.81]
})

display(results)

             Model  Hits@1  Hits@3   MRR    F1
0     Markov Chain    0.72    0.81  0.74  0.71
1  TransE / RotatE    0.78    0.87  0.80  0.77
2      GAT / R-GCN    0.82    0.90  0.84  0.83
3     Temporal GNN    0.85    0.92  0.87  0.86
4         LLM-only    0.80    0.88  0.82  0.81

In [130]:
results.to_csv("Experiment3_Results.csv", index=False)

print("Experiment 3 completed successfully")

Experiment 3 completed successfully

In [131]:
import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        print(os.path.join(root, file))

/content/Attack_Knowledge_Graph.json
/content/Extracted_data_1.json
/content/Experiment3_Results.csv
/content/APT_Knowledge_Graph.json
/content/MitreEnterprise (1).xlsx
/content/attackmitre (1).xlsx
/content/.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
/content/.config/active_config
/content/.config/.last_survey_prompt.yaml
/content/.config/.last_update_check.json
/content/.config/.last_opt_in_prompt.yaml
/content/.config/config_sentinel
/content/.config/default_configs.db
/content/.config/gce
/content/.config/logs/2026.06.04/13.32.38.346437.log
/content/.config/logs/2026.06.04/13.32.39.344962.log
/content/.config/logs/2026.06.04/13.32.02.654775.log
/content/.config/logs/2026.06.04/13.32.21.210570.log
/content/.config/logs/2026.06.04/13.31.42.499627.log
/content/.config/logs/2026.06.04/13.32.18.735754.log
/content/.config/configurations/config_default
/content/drive/MyDrive/Untitled document (1).gdoc
/content/drive/MyDrive/AP24110011352  Sai harishma .C PROGRAMING _copy.pdf
/content/drive/MyDrive/PXL_20240911_061511825.jpg
/content/drive/MyDrive/PXL_20240911_061508863.MP.jpg
/content/drive/MyDrive/PXL_20240911_061458304.jpg
/content/drive/MyDrive/Audio from .
/content/drive/MyDrive/physics-for-scientists-7th-ed_copy.pdf
/content/drive/MyDrive/Adobe Scan Sep 29, 2024.pdf
/content/drive/MyDrive/AP24110011352, aplitude assignment.pdf
/content/drive/MyDrive/AP24110011352,Aplitude assignment.pdf
/content/drive/MyDrive/IMG-20241018-WA0014.jpg
/content/drive/MyDrive/PXL_20241020_081151427.LONG_EXPOSURE-01.COVER.jpg
/content/drive/MyDrive/PXL_20241020_085151882.jpg
/content/drive/MyDrive/PXL_20241020_093430721.jpg
/content/drive/MyDrive/IMG_8310.JPG
/content/drive/MyDrive/Image.jpg
/content/drive/MyDrive/IMG-20241020-WA0007 (1).jpg
/content/drive/MyDrive/IMG-20241020-WA0007.jpg
/content/drive/MyDrive/FIC-103 AP24110011904.pdf
/content/drive/MyDrive/Assignment 2.pdf
/content/drive/MyDrive/DOC-20240814-WA0001..pdf
/content/drive/MyDrive/ id card.pdf
/content/drive/MyDrive/Case study of non verbal communication  (1).gdoc
/content/drive/MyDrive/DOC-20250325-WA0010..pdf
/content/drive/MyDrive/Non verbal communication (1).pdf
/content/drive/MyDrive/Non verbal communication.pdf
/content/drive/MyDrive/Body language and Nonverbal Communication.gdoc
/content/drive/MyDrive/Power of non verbal communication .gdoc
/content/drive/MyDrive/Case study of non verbal communication .gdoc
/content/drive/MyDrive/POLICYPAL report .pdf
/content/drive/MyDrive/POLICYPAL.pdf
/content/drive/MyDrive/Adobe Scan Apr 27, 2025.pdf
/content/drive/MyDrive/AP24110011352,EEE assignment 1.pdf
/content/drive/MyDrive/AP24110011352 eee assignment 1.pdf
/content/drive/MyDrive/Untitled document.gdoc
/content/drive/MyDrive/AP24110011352 (1).pdf
/content/drive/MyDrive/DOC-20250902-WA0013..pdf
/content/drive/MyDrive/AP24110011352.pdf
/content/drive/MyDrive/apaar id.pdf
/content/drive/MyDrive/DFS using Backtracking -DAA(AP24110011352).pdf
/content/drive/MyDrive/DFS using backtracking
/content/drive/MyDrive/compressed-video (1).mp4
/content/drive/MyDrive/video to text transcription report EGL-273(AP24110011352).pdf
/content/drive/MyDrive/introduction to disability project report (AP24110011352).pdf
/content/drive/MyDrive/Unit-4 OOP using C--_copy.pdf
/content/drive/MyDrive/Unit-1 OOP using C--_copy (1).pdf
/content/drive/MyDrive/Unit-1 OOP using C--_copy.pdf
/content/drive/MyDrive/Unit-2 OOP using C--_copy.pdf
/content/drive/MyDrive/AP24110011352.jpg
/content/drive/MyDrive/functions pdf (AP24110011352).pdf
/content/drive/MyDrive/comprehensions.pdf(AP24110011352).pdf
/content/drive/MyDrive/AP24110011352-maths assignment 3.pdf
/content/drive/MyDrive/list comprehension  (1).pdf
/content/drive/MyDrive/list comprehension .pdf
/content/drive/MyDrive/recursion (1).pdf
/content/drive/MyDrive/recursion.pdf
/content/drive/MyDrive/lambda (1).pdf
/content/drive/MyDrive/lambda.pdf
/content/drive/MyDrive/Screenshot_20260222-231926.png
/content/drive/MyDrive/inbound4257315683461751898.png
/content/drive/MyDrive/1000242594.mp4
/content/drive/MyDrive/(AP24110011352) DBMS assignment -3.pdf
/content/drive/MyDrive/Sai_harishma_Resume (2) (1).pdf
/content/drive/MyDrive/Sai_harishma_Resume (2).pdf
/content/drive/MyDrive/DOC-20260324-WA0008..pdf
/content/drive/MyDrive/unstop solution (AP24110011352) (1).pdf
/content/drive/MyDrive/unstop solution (AP24110011352).pdf
/content/drive/MyDrive/microplastics emerging technologies cla 2 ppt.pdf
/content/drive/MyDrive/final report-AEC(AP24110011352).pdf
/content/drive/MyDrive/AEC-Final Report (AP24110011352) (1).pdf
/content/drive/MyDrive/AEC-Final Report (AP24110011352).pdf
/content/drive/MyDrive/AP24110011352(assignment -7).pdf
/content/drive/MyDrive/harishma new resume.pdf
/content/drive/MyDrive/RESUME(HARISHMA) (7).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (6).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (5).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (4).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (3).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (2).pdf
/content/drive/MyDrive/RESUME(HARISHMA) (1).pdf
/content/drive/MyDrive/Google Keep Document.gdoc
/content/drive/MyDrive/DOC-20260428-WA0023..pdf
/content/drive/MyDrive/InShot_20260429_233332697.mp4
/content/drive/MyDrive/InShot_20260502_233230769 (1).mp4
/content/drive/MyDrive/VID-20260502-WA0037~2 (3).mp4
/content/drive/MyDrive/VID-20260502-WA0037~2 (2).mp4
/content/drive/MyDrive/VID-20260502-WA0037~2 (1).mp4
/content/drive/MyDrive/VID-20260502-WA0037~2.mp4
/content/drive/MyDrive/Unit4_ch18_Concurrency control and recovery.pptx.pdf
/content/drive/MyDrive/DOC-20260506-WA0010..pdf
/content/drive/MyDrive/RESUME(HARISHMA).pdf
/content/drive/MyDrive/harishma(resume).pdf
/content/drive/MyDrive/RESUME-sai harishma.pdf
/content/drive/MyDrive/harishma-resume.pdf
/content/drive/MyDrive/statement of purpose .pdf
/content/drive/MyDrive/godey sai harishma -resume.pdf
/content/drive/MyDrive/Weekly Diary report for CSC students.docx
/content/drive/MyDrive/Colab Notebooks/Experiment_3_GraphRAG_TTP_Prediction.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled0.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled1.ipynb
/content/drive/MyDrive/Colab Notebooks/gtygftyhftyfs.ipynb
/content/drive/MyDrive/Colab Notebooks/fuctions.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of fuctions.ipynb
/content/drive/MyDrive/Colab Notebooks/comprehensions.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Maincomprehensions.ipynb
/content/drive/MyDrive/Colab Notebooks/Maincomprehensions.ipynb
/content/drive/MyDrive/Colab Notebooks/lambda.ipynb
/content/drive/MyDrive/Colab Notebooks/recursion.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of recursion.ipynb
/content/drive/MyDrive/Colab Notebooks/ lambda.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of  lambda.ipynb
/content/drive/MyDrive/Colab Notebooks/Loops and Operatirs.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Loops and Operatirs.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled2.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled3.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled4.ipynb
/content/drive/MyDrive/Colab Notebooks/Experiment_1_Entity_Relation_Extraction_MITRE_ATT&CK.ipynb
/content/drive/MyDrive/Colab Notebooks/Experiment3_TTP_Prediction_Actual.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Experiment_3_GraphRAG_TTP_Prediction.ipynb
/content/drive/MyDrive/Classroom/AP24110011352(DAA assignment).pdf
/content/drive/MyDrive/Classroom/apaar id
/content/drive/MyDrive/Classroom/apaar id.pdf
/content/drive/MyDrive/Classroom/AP24110011352-DAA assignment .pdf
/content/drive/MyDrive/Classroom/FIC 102 T/Adobe Scan Sep 11, 2024(Shared) - Adobe cloud storage
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 ,sai harishma godey , physics assignment(Shared) - Adobe cloud storage
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 (1).pdf
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 physics assignment.pdf
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352.pdf
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 pdf.pdf
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 assignment.pdf
/content/drive/MyDrive/Classroom/FIC 102 T/AP24110011352 assignment 3.pdf
/content/drive/MyDrive/Classroom/C programming Section T/C language assignment .pdf
/content/drive/MyDrive/Classroom/C programming Section T/C PROGRAMING-1.pdf
/content/drive/MyDrive/Classroom/C programming Section T/AP24110011352 C PROGRAMING.pdf
/content/drive/MyDrive/Classroom/C programming Section T/AP24110011352 C PROGRAMING_copy (1).pdf
/content/drive/MyDrive/Classroom/C programming Section T/AP24110011352 C PROGRAMING_copy.pdf
/content/drive/MyDrive/Classroom/C programming Section T/AP24110011352  Sai harishma .C PROGRAMING .pdf
/content/drive/MyDrive/Classroom/C programming Section T/AP24110011352,mid term assignment,c language.pdf
/content/drive/MyDrive/Classroom/FIC117-2025 CSE-T/AP24110011352,godey Sai harishma.pdf
/content/drive/MyDrive/Classroom/2024 - ENVIRONMENTAL SCIENCE - VAC 101 SEM : II - CSE - T/Harishma Godey | AP24110011352 - CLA 3.gdoc
/content/drive/MyDrive/Classroom/2024 - ENVIRONMENTAL SCIENCE - VAC 101 SEM : II - CSE - T/Environmental_Impact_Report[1] (1).docx
/content/drive/MyDrive/Classroom/2024 - ENVIRONMENTAL SCIENCE - VAC 101 SEM : II - CSE - T/Environmental_Impact_Report[1].docx
/content/drive/MyDrive/Classroom/CSE 203- Section S-DISCRETE MATHEMATICS S/AP24110011352 maths assignment .pdf
/content/drive/MyDrive/Classroom/CSE 203- Section S-DISCRETE MATHEMATICS S/AP24110011352(G.S.harishma), discrete mathematics assignment .pdf
/content/drive/MyDrive/Classroom/CSE 203- Section S-DISCRETE MATHEMATICS S/AP24110011352(maths assignment -3).pdf
/content/drive/MyDrive/Classroom/CSE 203- Section S-DISCRETE MATHEMATICS S/AP24110011352(maths assignment 5).pdf
/content/drive/MyDrive/Classroom/2025 - DIGITAL ELECTRONICS - CSE 207 SEM : III - CSE : S/AP24110011352,(DE assignment).pdf
/content/drive/MyDrive/Classroom/2025 - DIGITAL ELECTRONICS - CSE 207 SEM : III - CSE : S/group 12 DE presentation video
/content/drive/MyDrive/Classroom/2025 - DIGITAL ELECTRONICS - CSE 207 SEM : III - CSE : S/group 12 DE ppt.pdf
/content/drive/MyDrive/Classroom/2025 - DIGITAL ELECTRONICS - CSE 207 SEM : III - CSE : S/DE presentation video group 12
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/dbms assignment 2 (AP24110011352).pdf
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/dbms assignment 1 (AP24110011352).pdf
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/(AP24110011352) DBMS assignment -3.pdf
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/dbms assignment -4 (AP24110011352).pdf
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/dbms assignment 5(AP24110011352).pdf
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/DBMS_assign_6.docx
/content/drive/MyDrive/Classroom/2024 - DATABASE MANAGEMENT SYSTEMS - CSE 209 Sem : IV :  CSE : S/DBMS Assignment -7.pdf.docx
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352 (1).pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352-maths assignment 3.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352-maths assignment 3 (1).pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/ap24110011352 maths assignment 4.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352 maths assignment 6.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/ap24110011352 assignment 7.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/(AP24110011352) DBMS assignment -3.pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352(assignment -7).pdf
/content/drive/MyDrive/Classroom/2024 - PROBABILITY AND STATISTICS - CSE 208 Sem : IV :  CSE : S/AP24110011352(assignment -9).pdf
/content/drive/MyDrive/Classroom/OE - EMERGING CONTAMINANTS AND THEIR MANAGEMENT OPEN ELECTIVE/AP24110011352(CLA-3  PROJECT REPORT).docx
/content/drive/MyDrive/Classroom/OE - EMERGING CONTAMINANTS AND THEIR MANAGEMENT OPEN ELECTIVE/microplastics emerging technologies cla 2 ppt.pdf
/content/drive/MyDrive/Meeting Reports/2026-05-01 06:31 tpp-ksdd-ntr/2026-05-01 06:31 tpp-ksdd-ntr Attendance Report.gsheet
/content/sample_data/anscombe.json
/content/sample_data/README.md
/content/sample_data/mnist_train_small.csv
/content/sample_data/california_housing_train.csv
/content/sample_data/mnist_test.csv
/content/sample_data/california_housing_test.csv

In [132]:
import os
print(os.listdir())

['.config', 'Attack_Knowledge_Graph.json', 'Extracted_data_1.json', 'Experiment3_Results.csv', 'APT_Knowledge_Graph.json', 'MitreEnterprise (1).xlsx', 'attackmitre (1).xlsx', 'drive', 'sample_data']

In [133]:
for m in genai.list_models():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3.1-flash-lite
models/gemini-3-pro-image-preview
models/gemini-3-pro-image
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/gemini-3.1-flash-image
models/gemini-3.5-flash
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/antigravity-preview-05-2026
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview
models/gemini-3.5-live-translate-preview